In [1]:
import pandas as pd
import os
import warnings
warnings.filterwarnings('ignore')

In [2]:
path_to_data = r"../data/raw/t100 segment"

In [3]:
# This function reduces the memory usage of a DataFrame by downcasting numeric types
def downcast(df, verbose = True):
    start_memory = df.memory_usage().sum() / 1024 ** 2
    for col in df.columns:
        dtype_name = df[col].dtype.name
        if dtype_name == "object":
            pass
        elif dtype_name == "bool":
            df[col] = df[col].astype("int8")
        elif dtype_name.startswith("int") or (df[col].round() == df[col]).all():
            df[col] = pd.to_numeric(df[col], downcast = "integer")
        else:
            df[col] = pd.to_numeric(df[col], downcast = "float")
    end_memory = df.memory_usage().sum() / 1024 ** 2

    if verbose:
        print("{:.1f}% compressed".format(100 * (start_memory - end_memory) / start_memory))

    return df

In [4]:
# Get the list of all csv files in path_to_data and all subfolders
csv_files = []
for root, dirs, files in os.walk(path_to_data):
    for f in files:
        if f.endswith('.asc'):
            csv_files.append(os.path.join(root, f))
csv_files

['../data/raw/t100 segment\\_201801\\dd.db28ds.wac.201702.201801.asc',
 '../data/raw/t100 segment\\_201802\\dd.db28ds.wac.201703.201802.asc',
 '../data/raw/t100 segment\\_201803\\dd.db28ds.wac.201704.201803.asc',
 '../data/raw/t100 segment\\_201804\\dd.db28ds.wac.201705.201804.asc',
 '../data/raw/t100 segment\\_201805\\dd.db28ds.wac.201706.201805.asc',
 '../data/raw/t100 segment\\_201806\\dd.db28ds.wac.201707.201806.asc',
 '../data/raw/t100 segment\\_201807\\dd.db28ds.wac.201708.201807.asc',
 '../data/raw/t100 segment\\_201808\\dd.db28ds.wac.201709.201808.asc',
 '../data/raw/t100 segment\\_201809\\dd.db28ds.wac.201710.201809.asc',
 '../data/raw/t100 segment\\_201810\\dd.db28ds.wac.201711.201810.asc',
 '../data/raw/t100 segment\\_201811\\dd.db28ds.wac.201712.201811.asc',
 '../data/raw/t100 segment\\_201812\\dd.db28ds.wac.201801.201812.asc',
 '../data/raw/t100 segment\\_201901\\dd.db28ds.wac.201802.201901.asc',
 '../data/raw/t100 segment\\_201902\\dd.db28ds.wac.201803.201902.asc',
 '../data/raw/t100 segment\\_201903\\dd.db28ds.wac.201804.201903.asc',
 '../data/raw/t100 segment\\_201904\\dd.db28ds.wac.201805.201904.asc',
 '../data/raw/t100 segment\\_201905\\dd.db28ds.wac.201806.201905.asc',
 '../data/raw/t100 segment\\_201906\\dd.db28ds.wac.201807.201906.asc',
 '../data/raw/t100 segment\\_201907\\dd.db28ds.wac.201808.201907.asc',
 '../data/raw/t100 segment\\_201908\\dd.db28ds.wac.201809.201908.asc',
 '../data/raw/t100 segment\\_201909\\dd.db28ds.wac.201810.201909.asc',
 '../data/raw/t100 segment\\_201910\\dd.db28ds.wac.201811.201910.asc',
 '../data/raw/t100 segment\\_201911\\dd.db28ds.wac.201812.201911.asc',
 '../data/raw/t100 segment\\_201912\\dd.db28ds.wac.201901.201912.asc',
 '../data/raw/t100 segment\\_202001\\db28seg.dd.wac.201902.202001.asc',
 '../data/raw/t100 segment\\_202002\\db28seg.dd.wac.201903.202002.asc',
 '../data/raw/t100 segment\\_202003\\db28seg.dd.wac.201904.202003.asc',
 '../data/raw/t100 segment\\_202004\\db28seg.dd.wac.201905.202004.asc',
 '../data/raw/t100 segment\\_202005\\db28seg.dd.wac.201906.202005.asc',
 '../data/raw/t100 segment\\_202006\\db28seg.dd.wac.201907.202006.asc',
 '../data/raw/t100 segment\\_202007\\db28seg.dd.wac.201908.202007.asc',
 '../data/raw/t100 segment\\_202008\\db28seg.dd.wac.201909.202008.asc',
 '../data/raw/t100 segment\\_202009\\db28seg.dd.wac.201910.202009.asc',
 '../data/raw/t100 segment\\_202010\\db28seg.dd.wac.201911.202010.asc',
 '../data/raw/t100 segment\\_202011\\db28seg.dd.wac.201912.202011.asc',
 '../data/raw/t100 segment\\_202012\\db28seg.dd.wac.202001.202012.asc',
 '../data/raw/t100 segment\\_202101\\db28seg.dd.wac.202002.202101.asc',
 '../data/raw/t100 segment\\_202102\\db28seg.dd.wac.202003.202102.asc',
 '../data/raw/t100 segment\\_202103\\db28seg.dd.wac.202004.202103.asc',
 '../data/raw/t100 segment\\_202104\\db28seg.dd.wac.202005.202104.asc',
 '../data/raw/t100 segment\\_202105\\db28seg.dd.wac.202006.202105.asc',
 '../data/raw/t100 segment\\_202106\\db28seg.dd.wac.202007.202106.asc',
 '../data/raw/t100 segment\\_202107\\db28seg.dd.wac.202008.202107.asc',
 '../data/raw/t100 segment\\_202108\\db28seg.dd.wac.202009.202108.asc',
 '../data/raw/t100 segment\\_202109\\db28seg.dd.wac.202010.202109.asc',
 '../data/raw/t100 segment\\_202110\\db28seg.dd.wac.202011.202110.asc',
 '../data/raw/t100 segment\\_202111\\db28seg.dd.wac.202012.202111.asc',
 '../data/raw/t100 segment\\_202112\\db28seg.dd.wac.202101.202112.asc',
 '../data/raw/t100 segment\\_202201\\db28seg.dd.wac.202102.202201.asc',
 '../data/raw/t100 segment\\_202202\\db28seg.dd.wac.202103.202202.asc',
 '../data/raw/t100 segment\\_202203\\db28seg.dd.wac.202104.202203.asc',
 '../data/raw/t100 segment\\_202204\\db28seg.dd.wac.202105.202204.asc',
 '../data/raw/t100 segment\\_202205\\db28seg.dd.wac.202106.202205.asc',
 '../data/raw/t100 segment\\_202206\\db28seg.dd.wac.202107.202206.asc',
 '../data/raw/t100 segment\\_202207\\db28seg.dd.wac.202108.202207.asc',
 '../data/raw/t100 segment\\_202208\\db28seg.dd.wac.202109.202208.asc',
 '../data/raw/t100 segment\\_202209\\db28seg.dd.wac.202110.202209.asc',
 '../data/raw/t100 segment\\_202210\\db28seg.dd.wac.202111.202210.asc',
 '../data/raw/t100 segment\\_202211\\db28seg.dd.wac.202112.202211.asc',
 '../data/raw/t100 segment\\_202212\\db28seg.dd.wac.202201.202212.asc',
 '../data/raw/t100 segment\\_202301\\db28seg.dd.wac.202202.202301.asc',
 '../data/raw/t100 segment\\_202302\\db28seg.dd.wac.202203.202302.asc',
 '../data/raw/t100 segment\\_202303\\db28seg.dd.wac.202204.202303.asc',
 '../data/raw/t100 segment\\_202304\\db28seg.dd.wac.202205.202304.asc',
 '../data/raw/t100 segment\\_202305\\db28seg.dd.wac.202206.202305.asc',
 '../data/raw/t100 segment\\_202306\\db28seg.dd.wac.202207.202306.asc',
 '../data/raw/t100 segment\\_202307\\db28seg.dd.wac.202208.202307.asc',
 '../data/raw/t100 segment\\_202308\\db28seg.dd.wac.202209.202308.asc',
 '../data/raw/t100 segment\\_202309\\db28seg.dd.wac.202210.202309.asc',
 '../data/raw/t100 segment\\_202310\\db28seg.dd.wac.202211.202310.asc',
 '../data/raw/t100 segment\\_202311\\db28seg.dd.wac.202212.202311.asc',
 '../data/raw/t100 segment\\_202312\\db28seg.dd.wac.202301.202312.asc',
 '../data/raw/t100 segment\\_202401\\db28seg.dd.wac.202302.202401.asc',
 '../data/raw/t100 segment\\_202402\\db28seg.dd.wac.202303.202402.asc',
 '../data/raw/t100 segment\\_202403\\db28seg.dd.wac.202304.202403.asc',
 '../data/raw/t100 segment\\_202404\\db28seg.dd.wac.202305.202404.asc',
 '../data/raw/t100 segment\\_202405\\db28seg.dd.wac.202306.202405.asc',
 '../data/raw/t100 segment\\_202406\\db28seg.dd.wac.202307.202406.asc',
 '../data/raw/t100 segment\\_202407\\db28seg.dd.wac.202308.202407.asc',
 '../data/raw/t100 segment\\_202408\\db28seg.dd.wac.202309.202408.asc',
 '../data/raw/t100 segment\\_202409\\db28seg.dd.wac.202310.202409.asc',
 '../data/raw/t100 segment\\_202410\\db28seg.dd.wac.202311.202410.asc',
 '../data/raw/t100 segment\\_202411\\db28seg.dd.wac.202312.202411.asc',
 '../data/raw/t100 segment\\_202412\\db28seg.dd.wac.202401.202412.asc',
 '../data/raw/t100 segment\\_202501\\db28seg.dd.wac.202402.202501.asc']

In [5]:
def load_data(file):
    df = pd.read_csv(file, low_memory=False, encoding='latin-1', delimiter='|', header=None)
    df['source_file'] = file
    return df

In [6]:
# Loop through the files, limiting columns and appending to a df
for file in csv_files:
    if file == csv_files[0]:
        df_main = load_data(file)
    else:
        print(f"Loading {file}")
        df_temp = load_data(file)
        df_main = pd.concat([df_main, df_temp], ignore_index=True)

df_main = downcast(df_main, verbose = True)
df_main

Loading ../data/raw/t100 segment\_201802\dd.db28ds.wac.201703.201802.asc
Loading ../data/raw/t100 segment\_201803\dd.db28ds.wac.201704.201803.asc
Loading ../data/raw/t100 segment\_201804\dd.db28ds.wac.201705.201804.asc
Loading ../data/raw/t100 segment\_201805\dd.db28ds.wac.201706.201805.asc
Loading ../data/raw/t100 segment\_201806\dd.db28ds.wac.201707.201806.asc
Loading ../data/raw/t100 segment\_201807\dd.db28ds.wac.201708.201807.asc
Loading ../data/raw/t100 segment\_201808\dd.db28ds.wac.201709.201808.asc
Loading ../data/raw/t100 segment\_201809\dd.db28ds.wac.201710.201809.asc
Loading ../data/raw/t100 segment\_201810\dd.db28ds.wac.201711.201810.asc
Loading ../data/raw/t100 segment\_201811\dd.db28ds.wac.201712.201811.asc
Loading ../data/raw/t100 segment\_201812\dd.db28ds.wac.201801.201812.asc
Loading ../data/raw/t100 segment\_201901\dd.db28ds.wac.201802.201901.asc
Loading ../data/raw/t100 segment\_201902\dd.db28ds.wac.201803.201902.asc
Loading ../data/raw/t100 segment\_201903\dd.db28ds.wac.201804.201903.asc
Loading ../data/raw/t100 segment\_201904\dd.db28ds.wac.201805.201904.asc
Loading ../data/raw/t100 segment\_201905\dd.db28ds.wac.201806.201905.asc
Loading ../data/raw/t100 segment\_201906\dd.db28ds.wac.201807.201906.asc
Loading ../data/raw/t100 segment\_201907\dd.db28ds.wac.201808.201907.asc
Loading ../data/raw/t100 segment\_201908\dd.db28ds.wac.201809.201908.asc
Loading ../data/raw/t100 segment\_201909\dd.db28ds.wac.201810.201909.asc
Loading ../data/raw/t100 segment\_201910\dd.db28ds.wac.201811.201910.asc
Loading ../data/raw/t100 segment\_201911\dd.db28ds.wac.201812.201911.asc
Loading ../data/raw/t100 segment\_201912\dd.db28ds.wac.201901.201912.asc
Loading ../data/raw/t100 segment\_202001\db28seg.dd.wac.201902.202001.asc
Loading ../data/raw/t100 segment\_202002\db28seg.dd.wac.201903.202002.asc
Loading ../data/raw/t100 segment\_202003\db28seg.dd.wac.201904.202003.asc
Loading ../data/raw/t100 segment\_202004\db28seg.dd.wac.201905.202004.asc
Loading ../data/raw/t100 segment\_202005\db28seg.dd.wac.201906.202005.asc
Loading ../data/raw/t100 segment\_202006\db28seg.dd.wac.201907.202006.asc
Loading ../data/raw/t100 segment\_202007\db28seg.dd.wac.201908.202007.asc
Loading ../data/raw/t100 segment\_202008\db28seg.dd.wac.201909.202008.asc
Loading ../data/raw/t100 segment\_202009\db28seg.dd.wac.201910.202009.asc
Loading ../data/raw/t100 segment\_202010\db28seg.dd.wac.201911.202010.asc
Loading ../data/raw/t100 segment\_202011\db28seg.dd.wac.201912.202011.asc
Loading ../data/raw/t100 segment\_202012\db28seg.dd.wac.202001.202012.asc
Loading ../data/raw/t100 segment\_202101\db28seg.dd.wac.202002.202101.asc
Loading ../data/raw/t100 segment\_202102\db28seg.dd.wac.202003.202102.asc
Loading ../data/raw/t100 segment\_202103\db28seg.dd.wac.202004.202103.asc
Loading ../data/raw/t100 segment\_202104\db28seg.dd.wac.202005.202104.asc
Loading ../data/raw/t100 segment\_202105\db28seg.dd.wac.202006.202105.asc
Loading ../data/raw/t100 segment\_202106\db28seg.dd.wac.202007.202106.asc
Loading ../data/raw/t100 segment\_202107\db28seg.dd.wac.202008.202107.asc
Loading ../data/raw/t100 segment\_202108\db28seg.dd.wac.202009.202108.asc
Loading ../data/raw/t100 segment\_202109\db28seg.dd.wac.202010.202109.asc
Loading ../data/raw/t100 segment\_202110\db28seg.dd.wac.202011.202110.asc
Loading ../data/raw/t100 segment\_202111\db28seg.dd.wac.202012.202111.asc
Loading ../data/raw/t100 segment\_202112\db28seg.dd.wac.202101.202112.asc
Loading ../data/raw/t100 segment\_202201\db28seg.dd.wac.202102.202201.asc
Loading ../data/raw/t100 segment\_202202\db28seg.dd.wac.202103.202202.asc
Loading ../data/raw/t100 segment\_202203\db28seg.dd.wac.202104.202203.asc
Loading ../data/raw/t100 segment\_202204\db28seg.dd.wac.202105.202204.asc
Loading ../data/raw/t100 segment\_202205\db28seg.dd.wac.202106.202205.asc
Loading ../data/raw/t100 segment\_202206\db28seg.dd.wac.202107.202206.asc
Loading ../data/raw/t100 segment\_202207\db28seg.dd.wac.202108.202207.asc
Loading ../data/raw/t100 segment\_202208\db28seg.dd.wac.202109.202208.asc
Loading ../data/raw/t100 segment\_202209\db28seg.dd.wac.202110.202209.asc
Loading ../data/raw/t100 segment\_202210\db28seg.dd.wac.202111.202210.asc
Loading ../data/raw/t100 segment\_202211\db28seg.dd.wac.202112.202211.asc
Loading ../data/raw/t100 segment\_202212\db28seg.dd.wac.202201.202212.asc
Loading ../data/raw/t100 segment\_202301\db28seg.dd.wac.202202.202301.asc
Loading ../data/raw/t100 segment\_202302\db28seg.dd.wac.202203.202302.asc
Loading ../data/raw/t100 segment\_202303\db28seg.dd.wac.202204.202303.asc
Loading ../data/raw/t100 segment\_202304\db28seg.dd.wac.202205.202304.asc
Loading ../data/raw/t100 segment\_202305\db28seg.dd.wac.202206.202305.asc
Loading ../data/raw/t100 segment\_202306\db28seg.dd.wac.202207.202306.asc
Loading ../data/raw/t100 segment\_202307\db28seg.dd.wac.202208.202307.asc
Loading ../data/raw/t100 segment\_202308\db28seg.dd.wac.202209.202308.asc
Loading ../data/raw/t100 segment\_202309\db28seg.dd.wac.202210.202309.asc
Loading ../data/raw/t100 segment\_202310\db28seg.dd.wac.202211.202310.asc
Loading ../data/raw/t100 segment\_202311\db28seg.dd.wac.202212.202311.asc
Loading ../data/raw/t100 segment\_202312\db28seg.dd.wac.202301.202312.asc
Loading ../data/raw/t100 segment\_202401\db28seg.dd.wac.202302.202401.asc
Loading ../data/raw/t100 segment\_202402\db28seg.dd.wac.202303.202402.asc
Loading ../data/raw/t100 segment\_202403\db28seg.dd.wac.202304.202403.asc
Loading ../data/raw/t100 segment\_202404\db28seg.dd.wac.202305.202404.asc
Loading ../data/raw/t100 segment\_202405\db28seg.dd.wac.202306.202405.asc
Loading ../data/raw/t100 segment\_202406\db28seg.dd.wac.202307.202406.asc
Loading ../data/raw/t100 segment\_202407\db28seg.dd.wac.202308.202407.asc
Loading ../data/raw/t100 segment\_202408\db28seg.dd.wac.202309.202408.asc
Loading ../data/raw/t100 segment\_202409\db28seg.dd.wac.202310.202409.asc
Loading ../data/raw/t100 segment\_202410\db28seg.dd.wac.202311.202410.asc
Loading ../data/raw/t100 segment\_202411\db28seg.dd.wac.202312.202411.asc
Loading ../data/raw/t100 segment\_202412\db28seg.dd.wac.202401.202412.asc
Loading ../data/raw/t100 segment\_202501\db28seg.dd.wac.202402.202501.asc
48.3% compressed

,0,1,2,3,4,5,6,7,8,9,...,20,21,22,23,24,25,26,27,source_file,28
0,2017,5,05A,30005,1,"LITTLE SQUAW,ALASKA,USA",ANC,30299,1,"ANCHORAGE,ALASKA,USA",...,47000,0,0,148,0,96,84,10.0,../data/raw/t100 segment\_201801\dd.db28ds.wac...,NaN
1,2017,4,05A,30005,1,"LITTLE SQUAW,ALASKA,USA",FAI,31517,1,"FAIRBANKS,ALASKA,USA",...,2422,9,0,0,0,64,60,1.0,../data/raw/t100 segment\_201801\dd.db28ds.wac...,NaN
2,2017,4,05A,30005,1,"LITTLE SQUAW,ALASKA,USA",FAI,31517,1,"FAIRBANKS,ALASKA,USA",...,7266,27,11,884,0,208,196,1.0,../data/raw/t100 segment\_201801\dd.db28ds.wac...,NaN
3,2017,9,05A,30005,1,"LITTLE SQUAW,ALASKA,USA",FAI,31517,1,"FAIRBANKS,ALASKA,USA",...,18960,72,27,1203,0,448,416,1.0,../data/raw/t100 segment\_201801\dd.db28ds.wac...,NaN
4,2017,9,05A,30005,1,"LITTLE SQUAW,ALASKA,USA",FAI,31517,1,"FAIRBANKS,ALASKA,USA",...,7266,27,10,1017,0,238,226,1.0,../data/raw/t100 segment\_201801\dd.db28ds.wac...,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32482339,2024,9,ZXU,36353,15,"North Kingstown, RI",TEB,35167,21,"Teterboro, NJ",...,3450,8,1,0,0,54,36,10.0,../data/raw/t100 segment\_202501\db28seg.dd.wa...,NaN
32482340,2024,3,ZXU,36353,15,"North Kingstown, RI",TEB,35167,21,"Teterboro, NJ",...,6900,16,5,0,0,108,84,10.0,../data/raw/t100 segment\_202501\db28seg.dd.wa...,NaN
32482341,2024,8,ZXU,36353,15,"North Kingstown, RI",TEB,35167,21,"Teterboro, NJ",...,3450,8,2,0,0,84,54,10.0,../data/raw/t100 segment\_202501\db28seg.dd.wa...,NaN
32482342,2024,6,ZXU,36353,15,"North Kingstown, RI",TEB,35167,21,"Teterboro, NJ",...,6900,16,2,0,0,102,78,10.0,../data/raw/t100 segment\_202501\db28seg.dd.wa...,NaN
32482343,2024,7,ZXU,36353,15,"North Kingstown, RI",VWK,35656,22,"Saratoga Springs, NY",...,3450,8,2,0,0,54,42,10.0,../data/raw/t100 segment\_202501\db28seg.dd.wa...,NaN

In [7]:
# Add column names
df_main.columns = ['year', 'month', 
                   'orig_alpha_code', 'orig_num_code', 'orig_wac', 'orig_city', 
                   'dest_alpha_code', 'dest_num_code', 'dest_wac', 'dest_city', 
                   'carrier_alpha_code', 'carrier_entity_code', 'oai_group_code', 
                   'distance', 'service_class', 
                   'aircraft_group', 'aircraft_type', 'aircraft_config', 
                   'departures_performed', 'departures_scheduled',
                   'avail_capacity', 'avail_seats', 'num_passengers', 
                   'freight', 'mail', 'ramp_minutes', 'airborne_minutes', 'carrier_wac', 'source_file', 'end']

df_main.drop(columns=['end'], inplace=True)

In [8]:
df_main

,year,month,orig_alpha_code,orig_num_code,orig_wac,orig_city,dest_alpha_code,dest_num_code,dest_wac,dest_city,...,departures_scheduled,avail_capacity,avail_seats,num_passengers,freight,mail,ramp_minutes,airborne_minutes,carrier_wac,source_file
0,2017,5,05A,30005,1,"LITTLE SQUAW,ALASKA,USA",ANC,30299,1,"ANCHORAGE,ALASKA,USA",...,0,47000,0,0,148,0,96,84,10.0,../data/raw/t100 segment\_201801\dd.db28ds.wac...
1,2017,4,05A,30005,1,"LITTLE SQUAW,ALASKA,USA",FAI,31517,1,"FAIRBANKS,ALASKA,USA",...,0,2422,9,0,0,0,64,60,1.0,../data/raw/t100 segment\_201801\dd.db28ds.wac...
2,2017,4,05A,30005,1,"LITTLE SQUAW,ALASKA,USA",FAI,31517,1,"FAIRBANKS,ALASKA,USA",...,0,7266,27,11,884,0,208,196,1.0,../data/raw/t100 segment\_201801\dd.db28ds.wac...
3,2017,9,05A,30005,1,"LITTLE SQUAW,ALASKA,USA",FAI,31517,1,"FAIRBANKS,ALASKA,USA",...,0,18960,72,27,1203,0,448,416,1.0,../data/raw/t100 segment\_201801\dd.db28ds.wac...
4,2017,9,05A,30005,1,"LITTLE SQUAW,ALASKA,USA",FAI,31517,1,"FAIRBANKS,ALASKA,USA",...,0,7266,27,10,1017,0,238,226,1.0,../data/raw/t100 segment\_201801\dd.db28ds.wac...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32482339,2024,9,ZXU,36353,15,"North Kingstown, RI",TEB,35167,21,"Teterboro, NJ",...,0,3450,8,1,0,0,54,36,10.0,../data/raw/t100 segment\_202501\db28seg.dd.wa...
32482340,2024,3,ZXU,36353,15,"North Kingstown, RI",TEB,35167,21,"Teterboro, NJ",...,0,6900,16,5,0,0,108,84,10.0,../data/raw/t100 segment\_202501\db28seg.dd.wa...
32482341,2024,8,ZXU,36353,15,"North Kingstown, RI",TEB,35167,21,"Teterboro, NJ",...,0,3450,8,2,0,0,84,54,10.0,../data/raw/t100 segment\_202501\db28seg.dd.wa...
32482342,2024,6,ZXU,36353,15,"North Kingstown, RI",TEB,35167,21,"Teterboro, NJ",...,0,6900,16,2,0,0,102,78,10.0,../data/raw/t100 segment\_202501\db28seg.dd.wa...
32482343,2024,7,ZXU,36353,15,"North Kingstown, RI",VWK,35656,22,"Saratoga Springs, NY",...,0,3450,8,2,0,0,54,42,10.0,../data/raw/t100 segment\_202501\db28seg.dd.wa...

In [10]:
df_sample = df_main.sample(1000, random_state=1234)
df_sample.to_csv(r"../data/processed/t100_segment_sample.csv", index=False)

In [17]:
df_main.sort_values(by=['num_passengers'], ascending=False).head(n=50)

,year,month,orig_alpha_code,orig_num_code,orig_wac,orig_city,dest_alpha_code,dest_num_code,dest_wac,dest_city,...,departures_scheduled,avail_capacity,avail_seats,num_passengers,freight,mail,ramp_minutes,airborne_minutes,carrier_wac,source_file
3088748,2018,7,HNL,32134,2,"HONOLULU,HAWAII,USA",OGG,33830,2,"KAHULUI,HAWAII,USA",...,849,26884800,108672,95777,492915,0,35812,18548,10.0,../data/raw/t100 segment\_201809\dd.db28ds.wac...
5725862,2018,7,HNL,32134,2,"HONOLULU,HAWAII,USA",OGG,33830,2,"KAHULUI,HAWAII,USA",...,849,26884800,108672,95777,492915,0,35812,18548,10.0,../data/raw/t100 segment\_201904\dd.db28ds.wac...
3834021,2018,7,HNL,32134,2,"HONOLULU,HAWAII,USA",OGG,33830,2,"KAHULUI,HAWAII,USA",...,849,26884800,108672,95777,492915,0,35812,18548,10.0,../data/raw/t100 segment\_201811\dd.db28ds.wac...
6108961,2018,7,HNL,32134,2,"HONOLULU,HAWAII,USA",OGG,33830,2,"KAHULUI,HAWAII,USA",...,849,26884800,108672,95777,492915,0,35812,18548,10.0,../data/raw/t100 segment\_201905\dd.db28ds.wac...
5344078,2018,7,HNL,32134,2,"HONOLULU,HAWAII,USA",OGG,33830,2,"KAHULUI,HAWAII,USA",...,849,26884800,108672,95777,492915,0,35812,18548,10.0,../data/raw/t100 segment\_201903\dd.db28ds.wac...
2717852,2018,7,HNL,32134,2,"HONOLULU,HAWAII,USA",OGG,33830,2,"KAHULUI,HAWAII,USA",...,849,26884800,108672,95777,492915,0,35812,18548,10.0,../data/raw/t100 segment\_201808\dd.db28ds.wac...
4585789,2018,7,HNL,32134,2,"HONOLULU,HAWAII,USA",OGG,33830,2,"KAHULUI,HAWAII,USA",...,849,26884800,108672,95777,492915,0,35812,18548,10.0,../data/raw/t100 segment\_201901\dd.db28ds.wac...
4208942,2018,7,HNL,32134,2,"HONOLULU,HAWAII,USA",OGG,33830,2,"KAHULUI,HAWAII,USA",...,849,26884800,108672,95777,492915,0,35812,18548,10.0,../data/raw/t100 segment\_201812\dd.db28ds.wac...
6493019,2018,7,HNL,32134,2,"HONOLULU,HAWAII,USA",OGG,33830,2,"KAHULUI,HAWAII,USA",...,849,26884800,108672,95777,492915,0,35812,18548,10.0,../data/raw/t100 segment\_201906\dd.db28ds.wac...
3460741,2018,7,HNL,32134,2,"HONOLULU,HAWAII,USA",OGG,33830,2,"KAHULUI,HAWAII,USA",...,849,26884800,108672,95777,492915,0,35812,18548,10.0,../data/raw/t100 segment\_201810\dd.db28ds.wac...
2348360,2018,7,HNL,32134,2,"HONOLULU,HAWAII,USA",OGG,33830,2,"KAHULUI,HAWAII,USA",...,849,26884800,108672,95777,492915,0,35812,18548,10.0,../data/raw/t100 segment\_201807\dd.db28ds.wac...
4964221,2018,7,HNL,32134,2,"HONOLULU,HAWAII,USA",OGG,33830,2,"KAHULUI,HAWAII,USA",...,849,26884800,108672,95777,492915,0,35812,18548,10.0,../data/raw/t100 segment\_201902\dd.db28ds.wac...
3939486,2018,7,OGG,33830,2,"KAHULUI,HAWAII,USA",HNL,32134,2,"HONOLULU,HAWAII,USA",...,849,26894100,108672,93733,172433,0,32774,19602,10.0,../data/raw/t100 segment\_201811\dd.db28ds.wac...
4314929,2018,7,OGG,33830,2,"KAHULUI,HAWAII,USA",HNL,32134,2,"HONOLULU,HAWAII,USA",...,849,26894100,108672,93733,172433,0,32774,19602,10.0,../data/raw/t100 segment\_201812\dd.db28ds.wac...
4692313,2018,7,OGG,33830,2,"KAHULUI,HAWAII,USA",HNL,32134,2,"HONOLULU,HAWAII,USA",...,849,26894100,108672,93733,172433,0,32774,19602,10.0,../data/raw/t100 segment\_201901\dd.db28ds.wac...
3565788,2018,7,OGG,33830,2,"KAHULUI,HAWAII,USA",HNL,32134,2,"HONOLULU,HAWAII,USA",...,849,26894100,108672,93733,172433,0,32774,19602,10.0,../data/raw/t100 segment\_201810\dd.db28ds.wac...
5071079,2018,7,OGG,33830,2,"KAHULUI,HAWAII,USA",HNL,32134,2,"HONOLULU,HAWAII,USA",...,849,26894100,108672,93733,172433,0,32774,19602,10.0,../data/raw/t100 segment\_201902\dd.db28ds.wac...
5833875,2018,7,OGG,33830,2,"KAHULUI,HAWAII,USA",HNL,32134,2,"HONOLULU,HAWAII,USA",...,849,26894100,108672,93733,172433,0,32774,19602,10.0,../data/raw/t100 segment\_201904\dd.db28ds.wac...
2451861,2018,7,OGG,33830,2,"KAHULUI,HAWAII,USA",HNL,32134,2,"HONOLULU,HAWAII,USA",...,849,26894100,108672,93733,172433,0,32774,19602,10.0,../data/raw/t100 segment\_201807\dd.db28ds.wac...
6217154,2018,7,OGG,33830,2,"KAHULUI,HAWAII,USA",HNL,32134,2,"HONOLULU,HAWAII,USA",...,849,26894100,108672,93733,172433,0,32774,19602,10.0,../data/raw/t100 segment\_201905\dd.db28ds.wac...
3193109,2018,7,OGG,33830,2,"KAHULUI,HAWAII,USA",HNL,32134,2,"HONOLULU,HAWAII,USA",...,849,26894100,108672,93733,172433,0,32774,19602,10.0,../data/raw/t100 segment\_201809\dd.db28ds.wac...
6601284,2018,7,OGG,33830,2,"KAHULUI,HAWAII,USA",HNL,32134,2,"HONOLULU,HAWAII,USA",...,849,26894100,108672,93733,172433,0,32774,19602,10.0,../data/raw/t100 segment\_201906\dd.db28ds.wac...
5451705,2018,7,OGG,33830,2,"KAHULUI,HAWAII,USA",HNL,32134,2,"HONOLULU,HAWAII,USA",...,849,26894100,108672,93733,172433,0,32774,19602,10.0,../data/raw/t100 segment\_201903\dd.db28ds.wac...
2821862,2018,7,OGG,33830,2,"KAHULUI,HAWAII,USA",HNL,32134,2,"HONOLULU,HAWAII,USA",...,849,26894100,108672,93733,172433,0,32774,19602,10.0,../data/raw/t100 segment\_201808\dd.db28ds.wac...
2348364,2018,6,HNL,32134,2,"HONOLULU,HAWAII,USA",OGG,33830,2,"KAHULUI,HAWAII,USA",...,826,26152000,105728,89172,479493,0,35030,18054,10.0,../data/raw/t100 segment\_201807\dd.db28ds.wac...
5725869,2018,6,HNL,32134,2,"HONOLULU,HAWAII,USA",OGG,33830,2,"KAHULUI,HAWAII,USA",...,826,26152000,105728,89172,479493,0,35030,18054,10.0,../data/raw/t100 segment\_201904\dd.db28ds.wac...
1979501,2018,6,HNL,32134,2,"HONOLULU,HAWAII,USA",OGG,33830,2,"KAHULUI,HAWAII,USA",...,826,26152000,105728,89172,479493,0,35030,18054,10.0,../data/raw/t100 segment\_201806\dd.db28ds.wac...
3088742,2018,6,HNL,32134,2,"HONOLULU,HAWAII,USA",OGG,33830,2,"KAHULUI,HAWAII,USA",...,826,26152000,105728,89172,479493,0,35030,18054,10.0,../data/raw/t100 segment\_201809\dd.db28ds.wac...
6108969,2018,6,HNL,32134,2,"HONOLULU,HAWAII,USA",OGG,33830,2,"KAHULUI,HAWAII,USA",...,826,26152000,105728,89172,479493,0,35030,18054,10.0,../data/raw/t100 segment\_201905\dd.db28ds.wac...
2717843,2018,6,HNL,32134,2,"HONOLULU,HAWAII,USA",OGG,33830,2,"KAHULUI,HAWAII,USA",...,826,26152000,105728,89172,479493,0,35030,18054,10.0,../data/raw/t100 segment\_201808\dd.db28ds.wac...
4208935,2018,6,HNL,32134,2,"HONOLULU,HAWAII,USA",OGG,33830,2,"KAHULUI,HAWAII,USA",...,826,26152000,105728,89172,479493,0,35030,18054,10.0,../data/raw/t100 segment\_201812\dd.db28ds.wac...
4585796,2018,6,HNL,32134,2,"HONOLULU,HAWAII,USA",OGG,33830,2,"KAHULUI,HAWAII,USA",...,826,26152000,105728,89172,479493,0,35030,18054,10.0,../data/raw/t100 segment\_201901\dd.db28ds.wac...
4964267,2018,6,HNL,32134,2,"HONOLULU,HAWAII,USA",OGG,33830,2,"KAHULUI,HAWAII,USA",...,826,26152000,105728,89172,479493,0,35030,18054,10.0,../data/raw/t100 segment\_201902\dd.db28ds.wac...
5344081,2018,6,HNL,32134,2,"HONOLULU,HAWAII,USA",OGG,33830,2,"KAHULUI,HAWAII,USA",...,826,26152000,105728,89172,479493,0,35030,18054,10.0,../data/raw/t100 segment\_201903\dd.db28ds.wac...
3460753,2018,6,HNL,32134,2,"HONOLULU,HAWAII,USA",OGG,33830,2,"KAHULUI,HAWAII,USA",...,826,26152000,105728,89172,479493,0,35030,18054,10.0,../data/raw/t100 segment\_201810\dd.db28ds.wac...
3834037,2018,6,HNL,32134,2,"HONOLULU,HAWAII,USA",OGG,33830,2,"KAHULUI,HAWAII,USA",...,826,26152000,105728,89172,479493,0,35030,18054,10.0,../data/raw/t100 segment\_201811\dd.db28ds.wac...
5451722,2018,6,OGG,33830,2,"KAHULUI,HAWAII,USA",HNL,32134,2,"HONOLULU,HAWAII,USA",...,826,26150900,105728,88925,178136,0,32526,19248,10.0,../data/raw/t100 segment\_201903\dd.db28ds.wac...
3939480,2018,6,OGG,33830,2,"KAHULUI,HAWAII,USA",HNL,32134,2,"HONOLULU,HAWAII,USA",...,826,26150900,105728,88925,178136,0,32526,19248,10.0,../data/raw/t100 segment\_201811\dd.db28ds.wac...
3193103,2018,6,OGG,33830,2,"KAHULUI,HAWAII,USA",HNL,32134,2,"HONOLULU,HAWAII,USA",...,826,26150900,105728,88925,178136,0,32526,19248,10.0,../data/raw/t100 segment\_201809\dd.db28ds.wac...
6217148,2018,6,OGG,33830,2,"KAHULUI,HAWAII,USA",HNL,32134,2,"HONOLULU,HAWAII,USA",...,826,26150900,105728,88925,178136,0,32526,19248,10.0,../data/raw/t100 segment\_201905\dd.db28ds.wac...
4314924,2018,6,OGG,33830,2,"KAHULUI,HAWAII,USA",HNL,32134,2,"HONOLULU,HAWAII,USA",...,826,26150900,105728,88925,178136,0,32526,19248,10.0,../data/raw/t100 segment\_201812\dd.db28ds.wac...
2451854,2018,6,OGG,33830,2,"KAHULUI,HAWAII,USA",HNL,32134,2,"HONOLULU,HAWAII,USA",...,826,26150900,105728,88925,178136,0,32526,19248,10.0,../data/raw/t100 segment\_201807\dd.db28ds.wac...
5833869,2018,6,OGG,33830,2,"KAHULUI,HAWAII,USA",HNL,32134,2,"HONOLULU,HAWAII,USA",...,826,26150900,105728,88925,178136,0,32526,19248,10.0,../data/raw/t100 segment\_201904\dd.db28ds.wac...
2082753,2018,6,OGG,33830,2,"KAHULUI,HAWAII,USA",HNL,32134,2,"HONOLULU,HAWAII,USA",...,826,26150900,105728,88925,178136,0,32526,19248,10.0,../data/raw/t100 segment\_201806\dd.db28ds.wac...
4692330,2018,6,OGG,33830,2,"KAHULUI,HAWAII,USA",HNL,32134,2,"HONOLULU,HAWAII,USA",...,826,26150900,105728,88925,178136,0,32526,19248,10.0,../data/raw/t100 segment\_201901\dd.db28ds.wac...
5071073,2018,6,OGG,33830,2,"KAHULUI,HAWAII,USA",HNL,32134,2,"HONOLULU,HAWAII,USA",...,826,26150900,105728,88925,178136,0,32526,19248,10.0,../data/raw/t100 segment\_201902\dd.db28ds.wac...
3565781,2018,6,OGG,33830,2,"KAHULUI,HAWAII,USA",HNL,32134,2,"HONOLULU,HAWAII,USA",...,826,26150900,105728,88925,178136,0,32526,19248,10.0,../data/raw/t100 segment\_201810\dd.db28ds.wac...
2821857,2018,6,OGG,33830,2,"KAHULUI,HAWAII,USA",HNL,32134,2,"HONOLULU,HAWAII,USA",...,826,26150900,105728,88925,178136,0,32526,19248,10.0,../data/raw/t100 segment\_201808\dd.db28ds.wac...
10996559,2019,10,ATL,30397,34,"Atlanta, GA",MCO,31454,33,"Orlando, FL",...,479,23515320,93919,86623,67490,51068,40908,28628,10.0,../data/raw/t100 segment\_202006\db28seg.dd.wa...
12015109,2019,10,ATL,30397,34,"Atlanta, GA",MCO,31454,33,"Orlando, FL",...,479,23515320,93919,86623,67490,51068,40908,28628,10.0,../data/raw/t100 segment\_202009\db28seg.dd.wa...

In [18]:
df_main['carrier_alpha_code'].value_counts()

carrier_alpha_code
WN     3431862
UA     2739176
DL     2591235
OO     2081390
AA     1991400
        ...
EE         234
30Q         86
3BQ         24
29Q         15
8D           6
Name: count, Length: 154, dtype: int64

In [19]:
df_main.to_csv(f'{path_to_data}/t100_segment_combined.csv', index=False)